namespace Mews.Fiscalizations.Spain.Dto.XSD.SuministroInformacion
{
    [System.SerializableAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/SuministroInformacion.xsd")]
    public enum CountryMiembroType
    {
        DE,
        AT,
        BE,
        BG,
        CZ,
        CY,
        HR,
        DK,
        SK,
        SI,
        EE,
        FI,
        FR,
        GR,
        HU,
        IE,
        IT,
        LV,
        LT,
        LU,
        MT,
        NL,
        PL,
        PT,
        GB,
        RO,
        SE,
    }
}