namespace Mews.Fiscalization.Greece.Model
{
    public enum VatExemptionType
    {
        WithoutVatArticle3,
        WithoutVatArticle5,
        WithoutVatArticle13,
        WithoutVatArticle14,
        WithoutVatArticle16,
        WithoutVatArticle19,
        WithoutVatArticle22,
        WithoutVatArticle24,
        WithoutVatArticle25,
        WithoutVatArticle26,
        WithoutVatArticle27,
        WithoutVatArticle27SeagoingVessels,
        WithoutVatArticle271CSeagoingVessels,
        WithoutVatArticle28,
        WithoutVatArticle39,
        WithoutVatArticle39A,
        WithoutVatArticle40,
        WithoutVatArticle41,
        WithoutVatArticle47,
        VatIncludedArticle43,
        VatIncludedArticle44,
        VatIncludedArticle45,
        VatIncludedArticle46
    }
}
