namespace Mews.Fiscalizations.Basque.Dto
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "urn:ticketbai:emision")]
    [XmlRoot(Namespace = "urn:ticketbai:emision", IsNullable = false)]
    public class TicketBaiResponse
    {

        private Salida salidaField;

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Salida Salida
        {
            get
            {
                return salidaField;
            }
            set
            {
                salidaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "urn:ticketbai:emision")]
    public class Salida
    {

        private string identificadorTBAIField;

        private string fechaRecepcionField;

        private string estadoField;

        private string descripcionField;

        private string azalpenaField;

        private ResultadosValidacion[] resultadosValidacionField;

        private string cSVField;

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IdentificadorTBAI
        {
            get
            {
                return identificadorTBAIField;
            }
            set
            {
                identificadorTBAIField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FechaRecepcion
        {
            get
            {
                return fechaRecepcionField;
            }
            set
            {
                fechaRecepcionField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Estado
        {
            get
            {
                return estadoField;
            }
            set
            {
                estadoField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Descripcion
        {
            get
            {
                return descripcionField;
            }
            set
            {
                descripcionField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Azalpena
        {
            get
            {
                return azalpenaField;
            }
            set
            {
                azalpenaField = value;
            }
        }

        /// <remarks/>
        [XmlElement("ResultadosValidacion", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ResultadosValidacion[] ResultadosValidacion
        {
            get
            {
                return resultadosValidacionField;
            }
            set
            {
                resultadosValidacionField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CSV
        {
            get
            {
                return cSVField;
            }
            set
            {
                cSVField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "urn:ticketbai:emision")]
    public class ResultadosValidacion
    {

        private string codigoField;

        private string descripcionField;

        private string azalpenaField;

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Codigo
        {
            get
            {
                return codigoField;
            }
            set
            {
                codigoField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Descripcion
        {
            get
            {
                return descripcionField;
            }
            set
            {
                descripcionField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Azalpena
        {
            get
            {
                return azalpenaField;
            }
            set
            {
                azalpenaField = value;
            }
        }
    }

}