using System;
using System.Xml.Serialization;

namespace Mews.Fiscalization.Greece.Dto.Xsd
{
    [Serializable]
    public enum IncomeClassificationType
    {
        [XmlEnum("E3_106")]
        DestroyingInventorAndCommodities,
        [XmlEnum("E3_205")]
        DestroyingInventoryAndRawAndOtherMaterials,
        [XmlEnum("E3_210")]
        DestroyingInventoryAndProductsAndProductionInProgress,
        [XmlEnum("E3_305")]
        RawAndOtherMaterials,
        [XmlEnum("E3_310")]
        ProductsAndProductionInProgress,
        [XmlEnum("E3_318")]
        DestroyingInventoryAndProductionExpenses,
        [XmlEnum("E3_561_001")]
        WholesaleSalesOfGoodsAndServicesForTraders,
        [XmlEnum("E3_561_002")]
        WholesaleSalesOfGoodsAndServicesPursuantToArticle39A,
        [XmlEnum("E3_561_003")]
        RetailSalesOfGoodsAndServicesPrivateClientele,
        [XmlEnum("E3_561_004")]
        RetailSalesOfGoodsAndServicesPursuantToArticle39A,
        [XmlEnum("E3_561_005")]
        IntraCommunityForeignSalesOfGoodsAndServices,
        [XmlEnum("E3_561_006")]
        ThirdCountryForeignSalesOfGoodsAndServices,
        [XmlEnum("E3_561_007")]
        OtherSalesOfGoodsAndServices,
        [XmlEnum("E3_562")]
        OtherOrdinaryIncome,
        [XmlEnum("E3_563")]
        CreditInterestAndRelatedIncome,
        [XmlEnum("E3_564")]
        CreditExchangeDifferences,
        [XmlEnum("E3_565")]
        IncomeFromParticipation,
        [XmlEnum("E3_566")]
        ProfitsFromDisposingNonCurrentAssets,
        [XmlEnum("E3_567")]
        ProfitsFromTheReversalOfProvisionsAndImpairments,
        [XmlEnum("E3_568")]
        ProfitsFromMeasurementAtFairValue,
        [XmlEnum("E3_570")]
        ExtraordinaryIncomeAndProfits,
        [XmlEnum("E3_595")]
        SelfProductionExpenses,
        [XmlEnum("E3_596")]
        SubsidiesGrants,
        [XmlEnum("E3_597")]
        SubsidiesGrantsForInvestmentPurposesExpenseCoverage,
        [XmlEnum("E3_880_001")]
        WholesaleSalesOfFixedAssets,
        [XmlEnum("E3_880_002")]
        RetailSalesOfFixedAssets,
        [XmlEnum("E3_880_003")]
        IntraCommunityForeignSalesOfFixedAssets,
        [XmlEnum("E3_880_004")]
        ThirdCountryForeignSalesOfFixedAssets,
        [XmlEnum("E3_881_001")]
        WholesaleSalesOnBehalfOfThirdParties,
        [XmlEnum("E3_881_002")]
        RetailSalesOnBehalfOfThirdParties,
        [XmlEnum("E3_881_003")]
        IntraCommunityForeignSalesOnBehalfOfThirdParties,
        [XmlEnum("E3_881_004")]
        ThirdCountryForeignSalesOnBehalfOfThirdParties
    }
}
