namespace Mews.Fiscalization.Spain.Dto.XSD.SuministroInformacion
{
    [System.SerializableAttribute]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www2.agenciatributaria.gob.es/static_files/common/internet/dep/aplicaciones/es/aeat/ssii/fact/ws/SuministroInformacion.xsd")]
    public enum IdOperacionesTrascendenciaTributariaType
    {
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,
        [System.Xml.Serialization.XmlEnumAttribute("06")]
        Item06,
        [System.Xml.Serialization.XmlEnumAttribute("07")]
        Item07,
        [System.Xml.Serialization.XmlEnumAttribute("08")]
        Item08,
        [System.Xml.Serialization.XmlEnumAttribute("09")]
        Item09,
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,
        [System.Xml.Serialization.XmlEnumAttribute("13")]
        Item13,
        [System.Xml.Serialization.XmlEnumAttribute("14")]
        Item14,
        [System.Xml.Serialization.XmlEnumAttribute("15")]
        Item15,
        [System.Xml.Serialization.XmlEnumAttribute("16")]
        Item16,
    }
}