name: Build and test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      
    defaults:
      run:
        working-directory: src
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      env:
        certificate_data: ${{secrets.certificate_data}}
        certificate_password: ${{secrets.certificate_password}}
        issuer_tax_number: ${{secrets.issuer_tax_number}}
        receiver_tax_number: ${{secrets.receiver_tax_number}}
      run: dotnet test --no-restore --verbosity normal