using System;
using System.Xml.Serialization;

namespace Mews.Fiscalization.Greece.Dto.Xsd
{
    [Serializable]
    public enum ExpenseClassificationType
    {
        [XmlEnum("E3_101")]
        CommoditiesAtPeriodStart,
        [XmlEnum("E3_102_001")]
        FiscalYearCommodityPurchasesWholesale,
        [XmlEnum("E3_102_002")]
        FiscalYearCommodityPurchasesRetail,
        [XmlEnum("E3_102_003")]
        FiscalYearCommodityPurchasesGoodsUnderArticle39A,
        [XmlEnum("E3_102_004")]
        FiscalYearCommodityPurchasesForeignIntraCommunity,
        [XmlEnum("E3_102_005")]
        FiscalYearCommodityPurchasesForeignThirdCountries,
        [XmlEnum("E3_102_005")]
        FiscalYearCommodityPurchasesOthers,
        [XmlEnum("E3_104")]
        CommoditiesAtPeriodEnd,
        [XmlEnum("E3_201")]
        RawAndOtherMaterialsAtPeriodStartProduction,
        [XmlEnum("E3_202_001")]
        FiscalYearRawAndOtherMaterialPurchaseWholesale,
        [XmlEnum("E3_202_002")]
        FiscalYearRawAndOtherMaterialPurchaseRetail,
        [XmlEnum("E3_202_003")]
        FiscalYearRawAndOtherMaterialPurchaseForeignIntraCommunity,
        [XmlEnum("E3_202_004")]
        FiscalYearRawAndOtherMaterialPurchaseForeignThirdCountries,
        [XmlEnum("E3_202_005")]
        FiscalYearRawAndOtherMaterialPurchaseOthers,
        [XmlEnum("E3_204")]
        RawAndOtherMaterialStockAtPeriodEndProduction,
        [XmlEnum("E3_207")]
        ProductsAndProductionInProgressAtPeriodStartProduction,
        [XmlEnum("E3_209")]
        ProductsAndProductionInProgressAtPeriodEndProduction,
        [XmlEnum("E3_301")]
        RawAndOtherMaterialStockAtPeriodStartAgricultural,
        [XmlEnum("E3_302_001")]
        FiscalYearRawAndOtherMaterialPurchaseNetAmountWholesale,
        [XmlEnum("E3_302_002")]
        FiscalYearRawAndOtherMaterialPurchaseNetAmountRetail,
        [XmlEnum("E3_302_003")]
        FiscalYearRawAndOtherMaterialPurchaseNetAmountForeignIntraCommunity,
        [XmlEnum("E3_302_004")]
        FiscalYearRawAndOtherMaterialPurchaseNetAmountForeignThirdCountries,
        [XmlEnum("E3_302_005")]
        FiscalYearRawAndOtherMaterialPurchaseNetAmountOthers,
        [XmlEnum("E3_304")]
        RawAndOtherMaterialStockAtPeriodEndAgricultural,
        [XmlEnum("E3_307")]
        ProductsAndProductionInProgressAtPeriodStartAgricultural,
        [XmlEnum("E3_309")]
        ProductsAndProductionInProgressAtPeriodEndAgricultural,
        [XmlEnum("E3_312")]
        StockAtPeriodStart,
        [XmlEnum("E3_313_001")]
        AnimalPlantPurchasesWholesale,
        [XmlEnum("E3_313_002")]
        AnimalPlantPurchasesRetail,
        [XmlEnum("E3_313_003")]
        AnimalPlantPurchasesForeignIntraCommunity,
        [XmlEnum("E3_313_004")]
        AnimalPlantPurchasesForeignThirdCountries,
        [XmlEnum("E3_313_005")]
        AnimalPlantPurchasesOthers,
        [XmlEnum("E3_315")]
        StockAtPeriodEndAnimalPlantAgricultural,
        [XmlEnum("E3_581_001")]
        EmployeeBenefitsGrossEarnings,
        [XmlEnum("E3_581_002")]
        EmployeeBenefitsEmployerContributions,
        [XmlEnum("E3_581_003")]
        EmployeeBenefitsOtherBenefits,
        [XmlEnum("E3_582")]
        AssetMeasurementDamages,
        [XmlEnum("E3_583")]
        DebitExchangeDifferences,
        [XmlEnum("E3_584")]
        DamagesFromDisposingWithdrawingNonCurrentAssets,
        [XmlEnum("E3_585_001")]
        ForeignDomesticManagementFees,
        [XmlEnum("E3_585_002")]
        ExpendituresFromLinkedEnterprises,
        [XmlEnum("E3_585_003")]
        ExpendituresFromNonCooperativeStatesOrPrivilegedTaxRegimes,
        [XmlEnum("E3_585_004")]
        ExpendituresForInformationDayEvents,
        [XmlEnum("E3_585_005")]
        ReceptionAndHospitalityExpenses,
        [XmlEnum("E3_585_006")]
        TravelExpenses,
        [XmlEnum("E3_585_007")]
        SelfEmployedSocialSecurityContributions,
        [XmlEnum("E3_585_008")]
        CommissionAgentExpensesAndFeesOnBehalfOfFarmers,
        [XmlEnum("E3_585_009")]
        OtherFeesForDomesticServices,
        [XmlEnum("E3_585_010")]
        OtherFeesForForeignServices,
        [XmlEnum("E3_585_011")]
        Energy,
        [XmlEnum("E3_585_012")]
        Water,
        [XmlEnum("E3_585_013")]
        Telecommunications,
        [XmlEnum("E3_585_014")]
        Rents,
        [XmlEnum("E3_585_015")]
        AdvertisementAndPromotion,
        [XmlEnum("E3_585_016")]
        OtherExpenses,
        [XmlEnum("E3_586")]
        DebitInterestsAndRelatedExpenses,
        [XmlEnum("E3_587")]
        Amortisations,
        [XmlEnum("E3_588")]
        ExtraordinaryExpensesDamagesAndFines,
        [XmlEnum("E3_589")]
        Provisions,
        [XmlEnum("E3_882_001")]
        FiscalYearTangibleAssetPurchasesWholesale,
        [XmlEnum("E3_882_002")]
        FiscalYearTangibleAssetPurchasesRetail,
        [XmlEnum("E3_882_003")]
        FiscalYearTangibleAssetPurchasesForeignIntraCommunity,
        [XmlEnum("E3_882_004")]
        FiscalYearTangibleAssetPurchasesForeignThirdCountry,
        [XmlEnum("E3_883_001")]
        FiscalYearIntangibleAssetPurchasesWholesale,
        [XmlEnum("E3_883_002")]
        FiscalYearIntangibleAssetPurchasesRetail,
        [XmlEnum("E3_883_003")]
        FiscalYearIntangibleAssetPurchasesForeignIntraCommunity,
        [XmlEnum("E3_883_004")]
        FiscalYearIntangibleAssetPurchasesForeignThirdCountry,
        [XmlEnum("VAT_361")]
        DomesticPurchasesAndExpenditures,
        [XmlEnum("VAT_362")]
        PurchasesAndImportsOfInvestmentGoods,
        [XmlEnum("VAT_363")]
        OtherImportsExceptForInvestmentGoods,
        [XmlEnum("VAT_364")]
        IntraCommunityGoodsAcquisitions,
        [XmlEnum("VAT_365")]
        IntraCommunityServicesReceiptsPerArticle142A,
        [XmlEnum("VAT_366")]
        OtherRecipientActions
    }
}
