name: Build and test - Austria (Linux)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      
    defaults:
      run:
        working-directory: src/Austria/Mews.Fiscalizations.Austria.Tests
        
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Clean
      run: dotnet clean ./Mews.Fiscalizations.Austria.Tests.csproj --configuration Release && dotnet nuget locals all --clear
        
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
