 name: pr-automation-qa-move-on-close
 on:	
   pull_request:
     types: [closed]
 jobs:	
   move-to-ready-to-test:	
     runs-on: ubuntu-latest	
     steps:	
       - name: Move to ready to test
         uses: alex-page/github-project-automation-plus@v0.8.0
         with:
           project: tech.review.qa
           column: Ready to test
           repo-token: ${{ secrets.TECH_ACCOUNT_PERSONAL_ACCESS_TOKEN }}
