name: Publish - Hungary

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      working-directory: src/Hungary/Mews.Fiscalizations.Hungary.Tests
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Clean
      run: dotnet clean ./Mews.Fiscalizations.Hungary.Tests.csproj --configuration Release && dotnet nuget locals all --clear
        
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore

  publish:
    runs-on: ubuntu-latest
    needs: build-and-test
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      working-directory: src/Hungary/Mews.Fiscalizations.Hungary
        
    steps:
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Pack
      run: dotnet pack -c Release -o out

    - name: Publish packages
      run: echo "Test publish"
