name: publish-fiskaly

on:
  workflow_run:
    workflows: [build-and-test-all]
    branches:
      - master
    types:
      - completed

jobs:
  publish-sweden:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    defaults:
      run:
        working-directory: src/Fiskaly/Mews.Fiscalizations.Fiskaly
        
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Pack
      run: dotnet pack -c Release -o out

    - name: Publish packages
      run: dotnet nuget push ./out/*.nupkg --skip-duplicate --source nuget.org --api-key ${{secrets.NUGET_TOKEN}}
